name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: test 
      run: |
        cd /home/ubuntu/nodebb/node_modules/nodebb-plugin-quickstart
        touch hello.txt
